# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

twitter_username: jekyllrb
github_username:  jekyll

pages: ./_static-pages
permalink: /articles/:title.html

paginate: 4
paginate_path: "/posts/page:num"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, bower_components]
gems: [jekyll-paginate]


# Development-Settings
# baseurl: "" # the subpath of your site, e.g. /my-furries
# url: "http://localhost:3000" # the base hostname & protocol for your site

# Production-Settings
baseurl: "/jekyll-theme-build" # the subpath of your site, e.g. /my-furries
url: "http://t3patterson.github.io" # the base hostname & protocol for your site
